---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger
  namespace: pinger
  labels: { app: pinger }
spec:
  replicas: 1
  selector:
    matchLabels: { app: pinger }
  template:
    metadata:
      labels: { app: pinger }
    spec:
      containers:
        - name: pinger
          image: ghcr.io/bruli/pinger:0.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - { name: TZ, value: Europe/Madrid }
            - name: NATS_SERVER_URL
              value: nats://nats.nats.svc.cluster.local:4222
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits:   { cpu: 200m, memory: 128Mi }
