---
apiVersion: v1
kind: Service
metadata:
  name: pinger
  namespace: pinger
  labels: { app: pinger }
spec:
  type: ClusterIP
  selector: { app: pinger }
  ports:
    - name: http
      port: 80
      targetPort: http
